# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Cybersecurity"
  pageRef = "cyber"
  weight = 2

[[main]]
  name = "Book Recommendations"
  pageRef = "books"
  weight = 3

[[main]]
name = "My Resume"
url  = "https://acrobat.adobe.com/id/urn:aaid:sc:US:fced42cb-5f5a-4da9-b688-8ba469f1f844"
weight = 4

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/reece-niemuth-mba-cissp-ccsp-54a87419a/"
  weight = 200

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/ReeceNiemuth"
  weight = 300

[[main]]
  identifier = "gitlab"
  pre = "gitlab"
  url = "https://gitlab.com/ReeceNiemuth"
  weight = 400

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


 [[footer]]
   name = "Recent Updates"
   pageRef = "changelog"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
